### ISSUE TITLE
General To-Do's

### ISSUE THREAD

**Issue by jstaffo3** [jstaffo3/runx5#1]
- [x] Make score not lerpX or lerpY

**Comment by mlow2** [comment]
Should we just put player movement in game.js? Don't know how to link files into the function

**Comment by mlow2** [comment]
- [ ] DRY up createEnemies
- [x] Add menu
- [x] Add point system
- [ ] Add powerups
- [x] Add spawns based off time/points
- [ ] Boss system

**Comment by rtoal** [comment]
Good checklist
